### ISSUE TITLE
"az foo => az network foo" doesn't work

### ISSUE THREAD

**Issue by tjprescott** [chewong/azure-cli-alias-extension#2]
This scenario is supposed to work if foo is not a top level keyword, but it does not.  Both of these failed:

az dns => az network dns
az cdn => az network cdn

**Comment by chewong** [comment]
The extension would actually consider the example above as recursive alias because you define `dns` as an alias, but the command it is referring to (`network dns`) contains the alias itself. So I slightly modified my implementation to simply reject any collided alias at any level for now. I will come up a solution to solve the problem

**Comment by tjprescott** [comment]
This is my primary use case for alias, so the fact that it's unsupported is disappointing.  

```
# ~/.azure/alias
[grp]
command = group

[ls]
command = list

[grp-ls]
command = grp ls
```

My expectation in this would be that if I tried "az grp-ls" then it would expand to "az grp ls" and that would simply fail because those don't correspond to anything. In that case, there would be no need for a recursive check.

**Comment by chewong** [comment]
Thanks for the suggestion, i'll definitely take this into account in the next iteration

**Comment by chewong** [comment]
@tjprescott,

I have updated the extension according to your suggestion above. Please give it a try!

```
$ rm ~/.azure/alias.sha1
$ az extension remove -n azure-cli-alias-extension
$ az extension add --source https://github.com/chewong/azure-cli-alias-extension/releases/download/0.0.2/azure_cli_alias_extension-0.0.2-py2.py3-none-any.whl -y

**Comment by tjprescott** [comment]
Interesting error!
```
(env) C:\Users\trpresco\Documents\github\azure-cli>az extension remove -n azure-cli-extension
The extension azure-cli-extension is not installed.

(env) C:\Users\trpresco\Documents\github\azure-cli>az extension add --source https://github.com/chewong/azure-cli-alias-extension/releases/download/0.0.2/azure_cli_alias_extension-0.0.2-py2.py3-none-any.whl -y
The extension azure-cli-alias-extension already exists.
```

**Comment by tjprescott** [comment]
I just deleted the folder to reinstall it, but there may be an issue with remove.

**Comment by tjprescott** [comment]
But yay it works!

**Comment by chewong** [comment]
should be `azure-cli-alias-extension` instead of `azure-cli-extension` in your first command, but glad it works!
