### ISSUE TITLE
alias extension breaks empty-string syntax in Azure CLI.

### ISSUE THREAD

**Issue by tjprescott** [chewong/azure-cli-alias-extension#3]
Before installing alias:
`az network vnet update -g {rg} -n {vnet} --dns-servers ""`

This worked and is used throughout our test cases.  Now I get:
```
(env) C:\Users\trpresco\Documents\github\azure-cli>az network vnet update -g tjp-rg -n vnet1 --dns-servers ""
az network vnet update: error: argument --dns-servers: expected at least one argument
```

When I examine the args, it has `[..., '--dns-servers']`  The empty-string entry is lost.  Removing the alias extension fixes the issue.

**Comment by chewong** [comment]
For each arg in args, I tried to removed any single or double quotes due to a bug related JEMSPath and my extension. That's probably why `""` is removed

**Comment by chewong** [comment]
Should be fixed:
```
$ az extension remove -n azure-cli-alias-extension
$ az extension add --source https://github.com/chewong/azure-cli-alias-extension/releases/download/0.0.2/azure_cli_alias_extension-0.0.2-py2.py3-none-any.whl -y
```
