### ISSUE TITLE
Error message for inconsistent placeholder not that helpful

### ISSUE THREAD

**Issue by derekbekoe** [chewong/azure-cli-alias-extension#4]
`version 0.0.1` of extension.

```
bash-4.3# az storage-connect
Inconsistent placeholder indexing in alias command
```

My alias file looks like this.
```
bash-4.3# cat ~/.azure/alias
[storage-connect {0} {1}]
command = az storage account connection-string -g {0} -n {1} -otsv
```

Maybe it should show that two positional arguments are required and print the alias definition?

**Comment by chewong** [comment]
I admit that the error messages aren't that helpful since I was focusing on the implementation of the extension. It will be improved in the future iteration

**Comment by chewong** [comment]
Please see #1
